name: CopyFiles from one repo to another

on:
  push:
    branches: []
      
  workflow_dispatch
  
jobs:
  push_code_job:
  
    name: Code push to server
    runs-on: ubuntu-latest

resources:
  repositories:
  - repository: abh1
    type: git
    name: folder1/*

steps:

- checkout: abh1
  clean: true
- checkout: self
  persistCredentials: true
  clean: true


- task: 
  displayName: "restore DestRepo"
  inputs:
    command: 'restore'
    projects: '$(Build.Repository.LocalPath)/abh2/folder1'
    feedsToUse: 'select'

- task: 
  displayName: "build DestRepo"
  inputs:
    command: 'build'
    projects: '$(Build.Repository.LocalPath)/abh2/folder1'
    configuration: Release

# Checkout the Git Code
- task: 
  displayName: checkout
  inputs:
    script: |
      git -C RootRep checkout $(Build.workflow)

- task: CmdLine@2
  displayName: pull
  inputs:
    script: |
      git -C workflow pull

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.Repository.LocalPath)\workflow\folder1'
    Contents: |
      **
    TargetFolder: '$(Build.Repository.LocalPath)\workflow\folder1'
    flattenFolders: false
    CleanTargetFolder: true
    OverWrite: true
    # preserveTimestamp: true

- task: CmdLine@2
  displayName: add
  inputs:
    script: |
      git -C workflow add --all

- task: CmdLine@2
  displayName: commit
  continueOnError: true
  inputs:
    script: |
      git -C DestRepo commit -m "Mulesoft Script & workflow added"

- task: CmdLine@2
  displayName: push
  inputs:
    script: |
      git -C workflow push -u origin $(Build.workflow)
