name: Mulesoft_Script file Deploy
on:
  push:
    branches:
      - workflow
  workflow_dispatch:
  
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetchdepth: 0
      - name: script push to New repo
        if: ${{ 'github.ref == refs/head/workflow' }}
        run: |
          echo "Pushing the script files to the Mulesoft server"
          echo ${{ env.branchname }}
          chmod 777 copyFiles.sh
          ./copyFiles.sh
